### ISSUE TITLE
Guarantees around `GuestMemory`

### ISSUE THREAD

**Issue by alexcrichton** [kubkon/wiggle#32]
One thing I'm personally pretty interested in is how far we can go with a safe API to reading/modifying guest memories. Skimming over the implementation here it's clear y'all are also very interested in this and have thought a lot about it!

Currently the safety looks like it'll work out (in my layman's opinion at least) but it does critically rely on two properties:

* One is that memories aren't shared. This is sort of a no-brainer but as soon as wasm gets threads all loads/stores are going to need to be at least somewhat-atomic and/or moved to wasmtime intrinsics of some form. This is less of a concern for now I think.
* The other though is that host implementations of functions can't be recursive in any form. For example you can't have a wasi function which calls back into wasm. That would open up situations where pointers could get invalidated with `memory.grow` or borrowing rules could be violated because the `GuestMemory` type is local to only one import.

I wanted to open this issue primarily about this second point, is it intended that this is a codified limitation that we aren't interested in lifting? I think this would mean that the wiggle traits would themselves need to be `unsafe` to promise they don't call back into wasm code via any shape or form. If we wanted to lift this limitation then the design is definitely pretty tricky and I think would require some nontrivial infrastructure in wasmtime too. Before I went down that thought road though wanted to canvas y'all :)

**Comment by pchickey** [comment]
Hi! Thanks for taking a look and helping us with wiggle, its great to have you here.

To be honest, I had not thought of the problem where host implementations can't be recursive. While wasi-common currently does not make recursive calls, we want it to be possible to call back in to the caller module's `malloc`, and for `memory.grow` to work correctly. So, yes, lets work on lifting this restriction.

I think the current design of `GuestPtr{Mut}` will be able to deal with a `GuestMemory` getting relocated, if the mutation is interior to `GuestMemory`.

Aside from recursive calls, for Lucet's implementation of our HTTP io calls, our current implementation uses https://docs.rs/lucet-runtime-internals/0.6.1/lucet_runtime_internals/vmctx/struct.Vmctx.html#method.yield_val_expecting_val so that we can swap back to a context where rust `async` works, so that probably has some safety issues I haven't thought through all the way. I'll work on making some representative calls open-source so we can figure out that model.

**Comment by kubkon** [comment]
>     * One is that memories aren't shared. This is sort of a no-brainer but as soon as wasm gets threads all loads/stores are going to need to be at least somewhat-atomic and/or moved to wasmtime intrinsics of some form. This is less of a concern for now I think.

Agreed! We can revisit this at a later stage I think.

> 
>     * The other though is that host implementations of functions can't be recursive in any form. For example you can't have a wasi function which calls back into wasm. That would open up situations where pointers could get invalidated with `memory.grow` or borrowing rules could be violated because the `GuestMemory` type is local to only one import.

This one is super interesting and I'd love for the API to safely support it, even if requires some nontrivial machinery both here, in `wasi-common`, and in `wasmtime`. Do you have a draft of a plan in mind @alexcrichton? I'd be more than happy share the workload, and maybe even come up with a more formal, written down plan of action we can work our way through.

**Comment by alexcrichton** [comment]
Ah ok, sounds like the recursive case is something we should try to tackle!

Without having to worry about threads, things things I can think of which may need to change are:

* `GuestMemory` shouldn't be a pointer/length pair, it'll need to point to some sort of `wasmtime` object which is an indirection to the pointer/length pair. For example it would ideally be `wasmtime::Memory` but we'll probably need to get by with `InstanceHandle` and `*mut VMMemoryDefinition` for now.

* Ideally we'd get as far as we can saying "you can't safely get `&T` into wasm memory". That would remove the need for the region borrowing and tracking that's implemented today. One of the hard parts with this is that if you can safely get a reference you need recursive callers to track who got that reference previously and somehow have shared state everywhere. I think that'd probably have to live in `wasmtime`, but it's also just generally a lot of bookeeping and would be best if we could avoid it. Do y'all know how feasible this is?

* Guaranteed safe operations we should be able to do are things like:
  * Copy data out of memory, e.g. read `i32` or copy out `Vec<u8>`
  * Copy data into memory, e.g. write `i32` or write a byte slice into memory

Well put another way I think we could boil this down to the first two. The first is pretty obvious because of `memory.grow`, and I'm curious to get y'all's thoughts on the second. Is there a critical use case requiring `&T` pointing into wasm memory?

**Comment by pchickey** [comment]
We can restructure GuestMemory that way, sure. One issue with making it wasmtime-specific is we still need to use it with Lucet as well. I think that GuestMemory can become, or use, a trait that Lucet and Wasmtime both implement efficiently.

The big motivation to take `&T` and `&[T]` into wasm memory is to implement reading and writing to iovecs (and similar) efficiently, whether to copy between modules, or pass directly to system calls. I wouldn't be eager to give up on one-copy IO, especially since interface types is going to such lengths to enable it.

However, I think using references to wasm memory like that and making recursive calls should be mutually exclusive - its required for safety, and I can't think of a good use case for holding a reference across a recursive call. Does that seem like an appropriate constraint, and one we could express in the type system?

**Comment by alexcrichton** [comment]
Oh good point, and yeah I think having a trait should work perfectly here. I suspect each crate could do something like `type MyGuestMemory = wiggle::GuestMemory<wasmtime::Memory>` or something like that to make it less verbose.

Also I should clarify, it's not inherently unsafe to create `&T` and `&[T]`, it's just unsafe to create those kinds of pointers *and* allow arbitrary code to run, because the arbitrary code running could call back into wasm and invalidate the pointers, unknowingly alias them, etc. In that sense I think we'd always have at the bare minimum unsafe methods or safe methods to extract `*const T` and `*const [T]`. 

Due to how highly aliased most wasm things are I don't think we can encode this into the type system unfortunately. Morally what's happening here is that the wasm instance sort of holds `Rc<Memory>` and then when you call a host function it gets a reference to that `Rc<Memory>` as well. Mutability is then "dynamically checked" rather than being statically knowable. That means that we can't statically forbid you calling back into wasm for a particular function, because we can't statically track down where all the moral `Rc<Memory>` things are going.

I could probably refine my question though, do y'all forsee *frequently* needing `&T` or `&[T]` to exist? If it's super frequent then we need to work harder to make it safe, but if it's few and far between then I think we could easily document what you need to do to be safe (aka "don't call back to wasm") and have some unsafe methods as an escape hatch.

**Comment by pchickey** [comment]
Cool, I can do that trait pretty quickly. My first guess is that the many places throughout the ptr/array code where we hold a `&GuestMemory` as a struct member is going to need the trait as well, so it will be a bit verbose, but throughout the code generator we should be able to be generic, and I don't think users are going to write the trait signature by hand very often. I'll see how it shakes out, unless you want to take it.

I believe that the need for `&T` and `&[T]` is relatively infrequent - for many calls in wasi, they wont be needed at all, because a copy is not costly. So, I think we can make the methods that create those refs `unsafe` if it allows us to always call recursive functions safely.

**Comment by kubkon** [comment]
I just wanted to point out here that deref to `&[T]` will not happen for `IovecArray` and cousins since those arrays hold non-transparent types (in this case, structs that themselves hold pointers to guest's memory). Currently, the main use of `&[T]` is for `GuestString` which can safely be derefed to `&str`, and having that seems pretty convenient for all `path_` syscalls that take relative path as an argument. I agree here with @pchickey that we can simply mark fns that create such refs `unsafe` since we *shouldn't* rely on them too much anyway.

**Comment by alexcrichton** [comment]
I think what will need to happen there is that `GuestString` will need to be threaded down to where the syscall actually happens. It's still not actually safe to ever get `&str` because we can't statically prove safety, but you know when any syscall is made that getting out `&str` is indeed safe because the OS doesn't hold on to the memory and the OS itself won't cause you to call back into wasm.

In that sense we'll need unsafety whenever we pass paths into the standard library, but that I think is fine and will be easy to verify as correct. It does unfortunately mean though that a lot of `unsafe` directives will need to be written down, which is unfortunate. We can't really isolate everything into a small handful of unsafe blocks.

**Comment by alexcrichton** [comment]
I don't mind playing around here to see what works! I might actually lean towards a trait to start off with, something like:

```rust
trait GuestMemory {
    // ptr/len accessors
}

struct GuestPtr<'a, T: ?Sized> {
    mem: &'a dyn GuestMemory + 'a,
    _data: PhantomData<&'a T>,
}

```


I think we could then get away with `GuestPtr<'a, [T]>` as well as `GuestPtr<'a, T>` everywhere. Something like `GuestPtr<'a, str>` would work too for reading/writing strings (and/or getting a string out)

**Comment by pchickey** [comment]
Ok cool I like that its a dyn access there because it should be pretty infrequent and adding the GuestMemory parameter to every single pointer was a drag in the 10 mins I found today to try prototyping it.

You could make the ptr/len accessors `unsafe` and then bubble out that annotation to everywhere its required. Hopefully its just creating a GuestRef / GuestRefMut that ends up being unsafe?

**Comment by kubkon** [comment]
So just to keep up with you guys here, what we're essentially saying is that operations on guest pointers are generally safe, so in the current `wiggle` lingo, that would be any type that is `GuestType`, and then we simply operate on `GuestPtr::read` and `GuestPtr::write` to pull and push bytes out and in. Whereas types that can be dereferenced to `&T`, etc., cannot be marked as safe as we have no way of statically proving safety of borrows, etc. Am I on the right track here?

And the current plan is to:
1. have a trait `GuestMemory` that will deref to pointer/length pair for creating a memory slice we can work with
2. generated types that reference guest's memory, `GuestPtr`, `GuestArray` (or `GuestPtr<[T]>`, I mean, however we name there), etc., will allow us to read bytes out and write bytes in
3. if there's a type we'd like to be dereferable to Rust's safe type, such as `&str`, we either mark it as `unsafe`, or forbid it (for now)

Sorry if I'm reiterating things here, I just need to organise this in my head ;-)

**Comment by alexcrichton** [comment]
Nah that all sounds about right @kubkon! The tl;dr; being that `&T` is never provably safe, so we're figuring out ways to minimize the unsafety associated with that property.

I should have a PR by the end of today sketching out what I'm thinking (I hope!)

**Comment by alexcrichton** [comment]
Ok I posted all my thoughts in https://github.com/kubkon/wiggle/pull/36

**Comment by pchickey** [comment]
This discussion ended up being extremely useful and I believe we've found satisfactory answers to the questions here.
